In [1]:
import pandas as pd

print(pd.__version__)

3.0.6

### SERIES Y DATAFRAMES

In [4]:
# Una SERIE es un array 1D
serie = pd.Series(
    [10,20,30],
    index=["a", "b", "c"],
    name= "ventas"
)

# Un DATAFRAME es un array 2D

df = pd.DataFrame(
    {
        "producto": ["A", "B"],
        "unidades": [10, 20]
    }
)

In [9]:
df

  producto  unidades
0        A        10
1        B        20

In [10]:
serie

a    10
b    20
c    30
Name: ventas, dtype: int64

### SERIES

In [11]:
serie_ventas = pd.Series(
    [120,85,200,45],
    index=["enero", "febrero", "marzo", "abril"],
    name="ventas"
)

serie_ventas

enero      120
febrero     85
marzo      200
abril       45
Name: ventas, dtype: int64

In [12]:
serie_ventas.mean()

np.float64(112.5)

In [13]:
serie_ventas.max()

np.int64(200)

In [14]:
serie_ventas.min()

np.int64(45)

### DataFrames

#### crear Dataframe desde un diccionario

In [15]:
df = pd.DataFrame(
    {
        "producto": ["Laptop", "Monitor","Teclado"],
        "unidades": [3, 7, 12],
        "precio": [1200, 320, 95]
    }
)

df

  producto  unidades  precio
0   Laptop         3    1200
1  Monitor         7     320
2  Teclado        12      95

#### Desde una lista de diccionarios

In [17]:
df2 = pd.DataFrame(
    [
        {"producto": "Laptop", "unidades": 3, "precio": 1200},
        {"producto": "Monitor", "unidades": 7, "precio": 320}
    ]
)

df2

  producto  unidades  precio
0   Laptop         3    1200
1  Monitor         7     320

#### Desde una lista de listas

In [18]:
df3 = pd.DataFrame(
    [
        ["Laptop",3,1200],
        ["Monitor",7,320]
    ],
    columns=["producto", "unidades", "precio"]
)

df3

  producto  unidades  precio
0   Laptop         3    1200
1  Monitor         7     320

#### Columnas calculadas

In [19]:
df = pd.DataFrame(
    {
        "producto": ["Laptop", "Monitor","Teclado"],
        "unidades": [3, 7, 12],
        "precio": [1200, 320, 95]
    }
)

df

  producto  unidades  precio
0   Laptop         3    1200
1  Monitor         7     320
2  Teclado        12      95

In [20]:
df["importe"] = df["unidades"] * df["precio"]
df

  producto  unidades  precio  importe
0   Laptop         3    1200     3600
1  Monitor         7     320     2240
2  Teclado        12      95     1140

In [24]:
df["unidades"].min()

np.int64(3)

In [21]:
### Devuelve las dimensiones del DataFrame
df.shape

(3, 4)

In [22]:
df.columns.to_list()

['producto', 'unidades', 'precio', 'importe']